# Generated by Django 4.0.2 on 2022-02-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_review_orderitem_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/'),
        ),
    ]
